import Slider from "../Services/Slider";
import "./View.css";

function View() {
  return (
    <div className="view">
      <p>
        <h2>
          Experience Effortless and Secure Information Governance and
          Management:
        </h2>
        <Slider />
        <div className="over">
          <div className="overview">
            <h4>SpotFile RECORD MANAGEMENT COMPANY</h4>
            <p>
              Complete and customised archives and records management solutions
              to meet all your company’s archiving needs. AGS Records Management
              company offers you a wide range of archiving services, from
              auditing and training, digital imaging to the professional
              management and archiving of your physical and digital documents.
            </p>
            <div className="ov">
              <img src="/Images/04.jpeg" alt="" />
              <p>
                Document archiving consists of conserving and storing documents,
                records and information in a safe and secure manner, which
                requires the assistance of archiving software in order to manage
                the high volume of documents generated by companies every year.{" "}
                <br /> <br />
                AGS Records Management company offers highly secure document
                storage solutions, while allowing you immediate digital and
                physical access to your documents. <br /> <br /> In addition, we
                also handle the safe and confidential disposal of your records.
                By outsourcing their records management, our clients can focus
                on their core business, and save time and money on managing
                their records.
              </p>
            </div>
            <button>
              <a href="/contact">Contact Us</a>
            </button>
          </div>
        </div>
      </p>
    </div>
  );
}

export default View;
